name: Build APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'

      # Записываем google-services.json из секрета — в коде его нет
      - name: Write google-services.json
        run: |
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' \
            > android/app/google-services.json

      - name: Get dependencies
        run: flutter pub get

      - name: Create gradlew
        run: |
          ls android/gradlew 2>/dev/null || (cd android && gradle wrapper --gradle-version 8.6)
          chmod +x android/gradlew

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d \
            > ${{ github.workspace }}/sscollective-key.jks

      - name: Build APK
        run: |
          flutter build apk --release \
            --dart-define=GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/sscollective-key.jks
          KEYSTORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          name: SSApp ${{ github.ref_name }}
          body: |
            - Added Russian language (Initial translation. May be rough)
            - Full Russification
            - If you have any corrections or want to help with the translation into Russian and other languages, contact: zynqff@gmail.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
