name: Build APK & AAB

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'

      - name: Write google-services.json
        run: |
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' \
            > android/app/google-services.json

      - name: Get dependencies
        run: flutter pub get

      - name: Generate launcher icons
        run: |
          rm -rf android/app/src/main/res/mipmap-hdpi
          rm -rf android/app/src/main/res/mipmap-mdpi
          rm -rf android/app/src/main/res/mipmap-xhdpi
          rm -rf android/app/src/main/res/mipmap-xxhdpi
          rm -rf android/app/src/main/res/mipmap-xxxhdpi
          dart run flutter_launcher_icons

      - name: Create gradlew
        run: |
          ls android/gradlew 2>/dev/null || (cd android && gradle wrapper --gradle-version 8.6)
          chmod +x android/gradlew

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d \
            > ${{ github.workspace }}/sscollective-key.jks

      - name: Build APK + AAB
        run: |
          cd android
          ./gradlew assembleRelease bundleRelease
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/sscollective-key.jks
          KEYSTORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/android/app/build/outputs/apk/release/app-arm64-v8a-release.apk
            ${{ github.workspace }}/android/app/build/outputs/apk/release/app-armeabi-v7a-release.apk
            ${{ github.workspace }}/android/app/build/outputs/apk/release/app-x86_64-release.apk
            ${{ github.workspace }}/android/app/build/outputs/apk/release/app-universal-release.apk
            ${{ github.workspace }}/android/app/build/outputs/bundle/release/app-release.aab
          name: SSApp ${{ github.ref_name }}
          body: |
            ### Для установки (APK)
            - **arm64-v8a** — все современные устройства (2017+), выбирай этот если не знаешь какой
            - **armeabi-v7a** — старые 32-bit устройства
            - **x86_64** — эмуляторы и Chromebook
            - **universal** — работает на всех, но весит больше

            ### Для магазинов (AAB)
            - **app-release.aab** — загружать в Рустор / Google Play
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
